services:
  db:
    image: postgres:16
    container_name: typer_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-typer}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-typer}
      POSTGRES_DB: ${POSTGRES_DB:-typer}
    ports:
      - "5432:5432"
    volumes:
      - typer_db_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: typer_mongo
    ports:
      - "27017:27017"
    volumes:
      - typer_mongo_data:/data/db

volumes:
  typer_db_data:
  typer_mongo_data:
